### ISSUE TITLE
Unauthorized error when creating the check

### ISSUE THREAD

**Issue by bencrouse** [gimenete/rubocop-action#1]
Not sure if this is a problem with this code or with the setup of our repo, but I thought I'd reach out to see if you had any insight. I'm getting a Unauthorized error, and when I lookup the (docs on the permissions)[https://developer.github.com/v3/checks/runs/#create-a-check-run] it says "Your GitHub App must have the checks:write permission to create check runs."

Any idea how Github Actions relate to this permissions-wise? Thanks!
https://github.com/workarea-commerce/workarea/runs/204931063#step:6:13

**Comment by andrewmcodes** [comment]
@bencrouse you need to add your github token to the environment. [Here](https://help.github.com/en/articles/virtual-environments-for-github-actions) is some documentation I found helpful when I hit this error.

Ex:
```yaml
- name: Rubocop checks
  uses: gimenete/rubocop-action@1.0
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Note: if you are using any dependencies of rubocop like `rubocop-rails`, `rubocop-performance`, etc. this action will not work for you. I am working on cooking up my solution for these cases.
