### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by himberjack** [gimenete/rubocop-action#5]
We are getting:
Successfully installed jaro_winkler-1.5.4
Successfully installed parallel-1.19.1
Successfully installed ast-2.4.0
Successfully installed parser-2.7.0.1
Successfully installed rainbow-3.0.0
Successfully installed ruby-progressbar-1.10.1
Successfully installed unicode-display_width-1.6.0
Successfully installed rubocop-0.79.0
8 gems installed
/action/lib/index.rb:39:in `create_check': Unauthorized (RuntimeError)
	from /action/lib/index.rb:119:in `run'
	from /action/lib/index.rb:134:in `<main>'
##[error]Docker run failed with exit code 1

**Comment by jotolo** [comment]
Did you set GITHUB_TOKEN? You can check #3 

```yml
- name: Rubocop checks
  uses: gimenete/rubocop-action@1.0
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
