### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by prashanth-sams** [gimenete/rubocop-action#6]
![image](https://user-images.githubusercontent.com/2948696/76287320-9ec0d500-62bd-11ea-83d7-271cb1754fcf.png)

```
- name: Rubocop checks
  uses: gimenete/rubocop-action@1.0
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by prashanth-sams** [comment]
Just updated the snippet with latest format and it works!!
```
name: Rubocop checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: gimenete/rubocop-action@1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
